jwt:
  secretKey: fuefoekwofkewofjoehfiuy87432u23hrjjfnjdfjsdfndfnefjenf4jj34j


spring:
  application:
    name: api-gateway



#api gateway config
  cloud:
    gateway:
      routes:
        - id: inventory-management-service
          uri : lb://INVENTORY-MANAGEMENT-SERVICE
          predicates:
            - Path=/inventory-mgmt-service/**
          filters:
            - name: Authentication
              args:
                isEnabled: false
        - id: order-management-service
          uri: lb://ORDER-MANAGEMENT-SERVICE
          predicates:
            - Path=/order-mgmt-service/**
          filters:
            - name: LoggingOrderFilter
            - name: Authentication
              args:
                isEnabled: false


#eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.110